# Generated by Django 2.0 on 2017-12-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20171210_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_2_digit',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_3_digit',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
