# Generated by Django 2.0 on 2018-01-07 14:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20171210_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevelEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('osm_type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('admin_level', models.PositiveIntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
            ],
        ),
    ]
