# Generated by Django 2.0 on 2018-01-07 14:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_adminlevelentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevelentry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
